name: "Base_workflow"

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      aws_default_region:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-20.04
    env:
      AWS_DEFAULT_REGION: ${{ inputs.aws_default_region }}
      AWS_ACCOUNT_ID: ${{ inputs.aws_account_id }}
    permissions:
      id-token: write
      contents: write


    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/gh_base_infra
          aws-region: ${{ inputs.aws_region }}
          role-duration-seconds: 2400
          role-session-name: ${{ github.event.repository.name }}

      # Install terraform
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5

      # Initialize
      - name: terraform init
        run: terraform init -backend=false

      # Validate
      - name: terraform validate
        run: terraform validate -no-color

      # Check terraform specs format
      - name: terraform fmt
        run: terraform fmt --recursive -check=true

      # Run terraform plan, save plan to file
      - name: terraform plan
        run: ./tf.sh plan -detailed-exitcode
