name: 'beta'

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * 0' # 06:00 UTC on Sun

jobs:
  beta:
    uses: cyber-dojo/terraform-base-infra/.github/workflows/base.yml@master
    with:
      aws_region: eu-central-1
      aws_account_id: 244531986313
      aws_default_region: eu-central-1