name: 'beta'

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * 0' # 06:00 UTC on Sun

jobs:
  beta:
    uses: fivexl/gh-workflow-tf-plan-apply/.github/workflows/base.yml@v0.0.1
    with:
      aws_region: eu-central-1
      aws_default_region: eu-central-1
      aws_role_arn: arn:aws:iam::244531986313:role/gh_base_infra
      working_directory: ./
      tf_apply: 'true'
