name: 'Beta Apply'

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}

jobs:
  apply:
    permissions:
      id-token: write
      contents: write
      pull-requests: read
    uses: kosli-dev/tf/.github/workflows/apply.yml@main
    strategy:
      fail-fast: false
    name: "Beta apply"
    with:
      aws_region: "eu-central-1"
      aws_role_arn: "arn:aws:iam::244531986313:role/gh_base_infra"
      environment: "beta"
      tf_version: v1.14.9
      kosli_host: ${{ vars.KOSLI_HOST }}
      kosli_org: cyber-dojo
      kosli_template_file: flow-templates/kosli-apply.yml
    secrets:
      kosli_api_token: ${{ secrets.KOSLI_API_TOKEN }}
      kosli_github_token: ${{ secrets.GITHUB_TOKEN }}

  kosli_attest_decision:
    needs: apply
    runs-on: ubuntu-latest
    name: "Kosli attest decision"
    env:
      KOSLI_ORG: cyber-dojo
      KOSLI_HOST: ${{ vars.KOSLI_HOST }}
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
      KOSLI_FLOW: ${{ needs.apply.outputs.kosli_flow }}
      KOSLI_TRAIL: ${{ needs.apply.outputs.kosli_trail }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@060e7f9bf6ac246743d6a62c5df847dfe7050867 # v5.2.1

      - name: Kosli attest decision
        run: |
          kosli attest decision \
            --control SDLC-CTRL-0002 \
            --compliant=true \
            --name provenance
