name: 'prod-pr-merged'

on:
  pull_request:
    branches: [ prod ]
    types: [ closed ]

concurrency:
  group: ${{ github.workflow }}

env:
  KOSLI_ORG: cyber-dojo-trails
  KOSLI_FLOW: "terraform-base-infra-prs"
  KOSLI_TRAIL: PR-${{ github.event.pull_request.number }}
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN_TRAILS }}
  KOSLI_HOST: ${{ vars.KOSLI_HOST }} # https://app.kosli.com
  KOSLI_DRY_RUN: ${{ vars.KOSLI_DRY_RUN }}
  KOSLI_CLI_VERSION: "2.7.1"

jobs:
  apply:
    if: github.event.pull_request.merged == true
    permissions:
      id-token: write
      contents: write
    uses: fivexl/gh-workflow-tf-plan-apply/.github/workflows/base.yml@v0.0.15
    with:
      aws_region: eu-central-1
      aws_default_region: eu-central-1
      aws_role_arn: arn:aws:iam::274425519734:role/gh_base_infra
      aws_role_duration: 900
      working_directory: ./
      tf_apply: 'true'
      tf_version: v1.4.5
      tf_upload_artifacts: 'true'
      tf_upload_artifact_path: "./plan.tfplan"

  trail-attest-tf-plan:
    needs: apply
    if: github.event.pull_request.merged == true
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kosli cli
        uses: kosli-dev/setup-cli-action@v2
        with:
          version:
            ${{ env.KOSLI_CLI_VERSION }}

      - name: Download a single artifact
        uses: actions/download-artifact@v4.1.1
        with:
          name: tf_artifacts
      
      - name: Attest tf plan to Kosli trail
        run:
          kosli attest generic
            --name tf-apply-plan
            --flow ${{ env.KOSLI_FLOW }}
            --trail ${{ env.KOSLI_TRAIL }}
            --evidence-paths ./plan.tfplan

      - name: Delete tf plan artifact
        run: |
          # Get the list of artifacts
          artifact_id=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository}}/actions/runs/${{ github.run_id }}/artifacts | jq -r '.artifacts[] | select(.name == "tf_artifacts").id')

          # Delete each artifact
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository}}/actions/artifacts/${artifact_id}

  attest-pull-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kosli cli
        uses: kosli-dev/setup-cli-action@v2
        with:
          version:
            ${{ env.KOSLI_CLI_VERSION }}

      - name: Attest PR to Kosli trail
        run:
          kosli attest pr github
            --name pull-request
            --flow ${{ env.KOSLI_FLOW }}
            --trail ${{ env.KOSLI_TRAIL }}
            --github-token ${{ secrets.GITHUB_TOKEN }}
