name: 'prod'

on:
  push:
    branches: [ prod ]
  schedule:
    - cron: '0 6 * * 0' # 06:00 UTC on Sun

jobs:
  prod:
    uses: fivexl/gh-workflow-tf-plan-apply/.github/workflows/base.yml@v0.0.3
    with:
      aws_region: eu-central-1
      aws_role_arn: arn:aws:iam::274425519734:role/gh_base_infra
      aws_default_region: eu-central-1
      working_directory: ./
